### ISSUE TITLE
parsedatetime 2.0 doesn't work on py26

### ISSUE THREAD

**Issue by bmw** [bear/parsedatetime#156]
```
(venv)[root@489884f36302 tmp.83QxkaCl7I]# pip freeze
parsedatetime==2.0
(venv)[root@489884f36302 tmp.83QxkaCl7I]# python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import parsedatetime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tmp.83QxkaCl7I/venv/lib/python2.6/site-packages/parsedatetime/__init__.py", line 44, in <module>
    from .pdt_locales import (locales as _locales,
  File "/tmp/tmp.83QxkaCl7I/venv/lib/python2.6/site-packages/parsedatetime/pdt_locales/__init__.py", line 10, in <module>
    from .icu import get_icu
  File "/tmp/tmp.83QxkaCl7I/venv/lib/python2.6/site-packages/parsedatetime/pdt_locales/icu.py", line 88
    result['dateFormats'] = {x: icu_df[x].toPattern() for x in keys}
                                                        ^
SyntaxError: invalid syntax
>>> 
```

**Comment by schoen** [comment]
(dictionary comprehensions don't exist prior to Python 2.7)

**Comment by bear** [comment]
@bmw @schoen -- see pr #157

**Comment by bear** [comment]
PR #157 merged - closing issue

**Comment by bmw** [comment]
@bear, do you know when a version of `parsedatetime` containing #157 will be released to PyPI?

**Comment by bear** [comment]
@bmw I can do that now...

**Comment by bmw** [comment]
Thanks again for being so unbelievably responsive. I'll update our repo to use v2.1.
