### ISSUE TITLE
OverflowError: date value out of range

### ISSUE THREAD

**Issue by VRGhost** [bear/parsedatetime#39]
The OverflowError is thrown if the `parse` method is called with `"7eda37ab-b1b0-3e0e-8786-248508232d93"` as an argument.

Code to replicate: `pdt.Calendar().parse("7eda37ab-b1b0-3e0e-8786-248508232d93")`.

Traceback by the current master revision (commit `9f8af907dbc4dbf3eb2a743a611871f361b83f62`):
```
Traceback (most recent call last):
  File "parsedatetime/tests/TestRegression.py", line 18, in testUnboundQuantity
    self.cal.parse("7eda37ab-b1b0-3e0e-8786-248508232d93")
  File "/home/ilo/Devel/Tattoo/parsedatetime/parsedatetime/__init__.py", line 1597, in parse
    totalTime = self._evalString(parseStr, totalTime)
  File "/home/ilo/Devel/Tattoo/parsedatetime/parsedatetime/__init__.py", line 1233, in _evalString
    sourceTime     = self._buildTime(sourceTime, quantity, modifier, units)
  File "/home/ilo/Devel/Tattoo/parsedatetime/parsedatetime/__init__.py", line 321, in _buildTime
    target        = start + datetime.timedelta(days=qty)
OverflowError: date value out of range
```

**Comment by bear** [comment]
The latest code no longer triggers an Overflow error and returns a "0 unable to parse" result in the result tuple
