### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by VRGhost** [bear/parsedatetime#40]
Its me again, calling `parse()` with more crazy inputs.

This time it is `659127,660214`.

```
Traceback (most recent call last):
  File "parsedatetime/tests/TestRegression.py", line 18, in testUnboundQuantity
    self.cal.parse("659127,660214")
  File "/home/ilo/Devel/Tattoo/parsedatetime/parsedatetime/__init__.py", line 1597, in parse
    totalTime = self._evalString(parseStr, totalTime)
  File "/home/ilo/Devel/Tattoo/parsedatetime/parsedatetime/__init__.py", line 1135, in _evalString
    hr, mn, sec = _extract_time(m)
  File "/home/ilo/Devel/Tattoo/parsedatetime/parsedatetime/__init__.py", line 114, in _extract_time
    seconds = int(seconds)
ValueError: invalid literal for int() with base 10: '27,660214'
```

**Comment by bear** [comment]
The latest code no longer triggers an Value error and returns a "0 unable to parse" result in the result tuple
